export const units: Sco.Model.UnitAsset[] = [
  {
    id: 'unit_spear',
    description: '',
    name: 'Spear',
    shootingSpeed: 400,
    accuracy: 55,
    evasion: 17,
    endurance: 900,
    firePower: 150,
    strategicCaliber: 300,
    armorType: Sco.Model.ArmorType.LIGHT,
    weaponType: Sco.Model.WeaponType.NORMAL,
    type: Sco.Model.UnitType.SMALL,
    speed: 3,
    gasConsumption: 2,
    foodConsumption: 2,
    cost: {
      GL: 150,
      IR: 20,
      MO: 0
    },
    techRequirements: [],
    productionTime: 1,
    features: []
  },
  {
    id: 'unit_explorer',
    description: '',
    name: 'Explorer',
    shootingSpeed: 300,
    accuracy: 30,
    evasion: 18,
    endurance: 1200,
    firePower: 200,
    strategicCaliber: 500,
    armorType: Sco.Model.ArmorType.LIGHT,
    weaponType: Sco.Model.WeaponType.NORMAL,
    type: Sco.Model.UnitType.SMALL,
    speed: 3,
    gasConsumption: 3,
    foodConsumption: 2,
    cost: {
      GL: 250,
      IR: 25,
      MO: 0
    },
    techRequirements: ['tech_smallShips'],
    productionTime: 1,
    features: []
  },
  {
    id: 'unit_crusader',
    description: '',
    name: 'Crusader',
    shootingSpeed: 500,
    accuracy: 70,
    evasion: 16,
    endurance: 1500,
    firePower: 300,
    strategicCaliber: 400,
    armorType: Sco.Model.ArmorType.LIGHT,
    weaponType: Sco.Model.WeaponType.ANTIARMOR,
    type: Sco.Model.UnitType.SMALL,
    speed: 3,
    gasConsumption: 4,
    foodConsumption: 3,
    cost: {
      GL: 150,
      IR: 40,
      MO: 0
    },
    techRequirements: ['tech_small_ships', 'tech_antiArmorLasers'],
    productionTime: 1,
    features: []
  },
  {
    id: 'unit_hawk',
    description: '',
    name: 'Hawk',
    shootingSpeed: 600,
    accuracy: 60,
    evasion: 19,
    endurance: 1500,
    firePower: 300,
    strategicCaliber: 400,
    armorType: Sco.Model.ArmorType.LIGHT,
    weaponType: Sco.Model.WeaponType.NORMAL,
    type: Sco.Model.UnitType.SMALL,
    speed: 4,
    gasConsumption: 3,
    foodConsumption: 3,
    cost: {
      GL: 200,
      IR: 30,
      MO: 0
    },
    techRequirements: ['tech_smallShips'],
    productionTime: 1,
    features: []
  },
  {
    id: 'unit_vessel',
    description: '',
    name: 'Vessel',
    shootingSpeed: 500,
    accuracy: 70,
    evasion: 16,
    endurance: 3500,
    firePower: 600,
    strategicCaliber: 400,
    armorType: Sco.Model.ArmorType.MEDIUM,
    weaponType: Sco.Model.WeaponType.NORMAL,
    type: Sco.Model.UnitType.MEDIUM,
    speed: 3,
    gasConsumption: 4,
    foodConsumption: 4,
    cost: {
      GL: 330,
      IR: 40,
      MO: 0
    },
    techRequirements: ['tech_mediumShips'],
    productionTime: 1,
    features: []
  },
  {
    id: 'unit_storm',
    description: '',
    name: 'Storm',
    shootingSpeed: 500,
    accuracy: 90,
    evasion: 13,
    endurance: 4500,
    firePower: 750,
    strategicCaliber: 500,
    armorType: Sco.Model.ArmorType.MEDIUM,
    weaponType: Sco.Model.WeaponType.BOMBS,
    type: Sco.Model.UnitType.MEDIUM,
    speed: 3,
    gasConsumption: 5,
    foodConsumption: 4,
    cost: {
      GL: 400,
      IR: 50,
      MO: 0
    },
    techRequirements: ['tech_mediumShips', 'tech_bombs'],
    productionTime: 2,
    features: []
  },
  {
    id: 'unit_massive',
    description: '',
    name: 'Massive',
    shootingSpeed: 500,
    accuracy: 70,
    evasion: 15,
    endurance: 5000,
    firePower: 800,
    strategicCaliber: 500,
    armorType: Sco.Model.ArmorType.MEDIUM,
    weaponType: Sco.Model.WeaponType.ANTIARMOR,
    type: Sco.Model.UnitType.MEDIUM,
    speed: 3,
    gasConsumption: 5,
    foodConsumption: 4,
    cost: {
      GL: 400,
      IR: 55,
      MO: 0
    },
    techRequirements: ['tech_mediumShips', 'tech_antiArmorLasers'],
    productionTime: 2,
    features: []
  },
  {
    id: 'unit_admiral',
    description: '',
    name: 'Admiral',
    shootingSpeed: 400,
    accuracy: 75,
    evasion: 13,
    endurance: 9000,
    firePower: 900,
    strategicCaliber: 500,
    armorType: Sco.Model.ArmorType.HEAVY,
    weaponType: Sco.Model.WeaponType.NORMAL,
    type: Sco.Model.UnitType.LARGE,
    speed: 3,
    gasConsumption: 5,
    foodConsumption: 5,
    cost: {
      GL: 600,
      IR: 60,
      MO: 0
    },
    techRequirements: ['tech_largeShips'],
    productionTime: 2,
    features: []
  },
  {
    id: 'unit_tornado',
    description: '',
    name: 'Tornado',
    shootingSpeed: 400,
    accuracy: 95,
    evasion: 10,
    endurance: 11000,
    firePower: 1000,
    strategicCaliber: 600,
    armorType: Sco.Model.ArmorType.HEAVY,
    weaponType: Sco.Model.WeaponType.BOMBS,
    type: Sco.Model.UnitType.LARGE,
    speed: 3,
    gasConsumption: 6,
    foodConsumption: 6,
    cost: {
      GL: 700,
      IR: 65,
      MO: 1
    },
    techRequirements: ['tech_largeShips', 'tech_bombs'],
    productionTime: 2,
    features: []
  },
  {
    id: 'unit_immortal',
    description: '',
    name: 'Immortal',
    shootingSpeed: 400,
    accuracy: 80,
    evasion: 12,
    endurance: 12000,
    firePower: 1100,
    strategicCaliber: 600,
    armorType: Sco.Model.ArmorType.HEAVY,
    weaponType: Sco.Model.WeaponType.ANTIARMOR,
    type: Sco.Model.UnitType.LARGE,
    speed: 3,
    gasConsumption: 6,
    foodConsumption: 6,
    cost: {
      GL: 750,
      IR: 70,
      MO: 1
    },
    techRequirements: ['tech_largeShips', 'tech_antiArmorLasers'],
    productionTime: 2,
    features: []
  },
  {
    id: 'unit_mothership',
    description: '',
    name: 'MotherShip',
    shootingSpeed: 400,
    accuracy: 100,
    evasion: 8,
    endurance: 20000,
    firePower: 2000,
    strategicCaliber: 700,
    armorType: Sco.Model.ArmorType.HEAVY,
    weaponType: Sco.Model.WeaponType.BOMBS,
    type: Sco.Model.UnitType.HUGE,
    speed: 2,
    gasConsumption: 8,
    foodConsumption: 9,
    cost: {
      GL: 1200,
      IR: 90,
      MO: 2
    },
    techRequirements: ['tech_hugeShips', 'Bombs'],
    productionTime: 3,
    features: []
  },
  {
    id: 'unit_tank',
    description: '',
    name: 'Tank',
    shootingSpeed: 300,
    accuracy: 50,
    evasion: 10,
    endurance: 10000,
    firePower: 300,
    strategicCaliber: 800,
    armorType: Sco.Model.ArmorType.MEDIUM,
    weaponType: Sco.Model.WeaponType.NORMAL,
    type: Sco.Model.UnitType.MEDIUM,
    speed: 3,
    gasConsumption: 6,
    foodConsumption: 5,
    cost: {
      GL: 500,
      IR: 80,
      MO: 0
    },
    techRequirements: ['tech_largeShips'],
    productionTime: 2,
    features: []
  },
  {
    id: 'unit_spy',
    description: '',
    name: 'Spy',
    shootingSpeed: 300,
    accuracy: 70,
    evasion: 18,
    endurance: 1200,
    firePower: 200,
    strategicCaliber: 700,
    armorType: Sco.Model.ArmorType.LIGHT,
    weaponType: Sco.Model.WeaponType.NORMAL,
    type: Sco.Model.UnitType.LARGE,
    speed: 3,
    gasConsumption: 3,
    foodConsumption: 3,
    cost: {
      GL: 400,
      IR: 30,
      MO: 0
    },
    techRequirements: ['tech_smallShips'],
    productionTime: 2,
    features: []
  },
  {
    id: 'unit_mercenary',
    description: '',
    name: 'Mercenary',
    shootingSpeed: 500,
    accuracy: 75,
    evasion: 13,
    endurance: 4000,
    firePower: 500,
    strategicCaliber: 400,
    armorType: Sco.Model.ArmorType.MEDIUM,
    weaponType: Sco.Model.WeaponType.NORMAL,
    type: Sco.Model.UnitType.MEDIUM,
    speed: 3,
    gasConsumption: 4,
    foodConsumption: 0,
    cost: {
      GL: 600,
      IR: 0,
      MO: 0
    },
    techRequirements: ['tech_largeShips'],
    productionTime: 1,
    features: []
  },
  {
    id: 'unit_warp',
    description: '',
    name: 'Warp',
    shootingSpeed: 300,
    accuracy: 60,
    evasion: 7,
    endurance: 3000,
    firePower: 300,
    strategicCaliber: 800,
    armorType: Sco.Model.ArmorType.HEAVY,
    weaponType: Sco.Model.WeaponType.NORMAL,
    type: Sco.Model.UnitType.HUGE,
    speed: 2,
    gasConsumption: 10,
    foodConsumption: 8,
    cost: {
      GL: 1000,
      IR: 80,
      MO: 5
    },
    techRequirements: ['Warp', 'tech_hugeShips'],
    productionTime: 3,
    features: []
  },
  {
    id: 'unit_b6',
    description: '',
    name: 'B6',
    shootingSpeed: 600,
    accuracy: 90,
    evasion: 12,
    endurance: 800,
    firePower: 200,
    strategicCaliber: 300,
    armorType: Sco.Model.ArmorType.LIGHT,
    weaponType: Sco.Model.WeaponType.NORMAL,
    type: Sco.Model.UnitType.LAND,
    speed: 0,
    gasConsumption: 0,
    foodConsumption: 1,
    cost: {
      GL: 150,
      IR: 10,
      MO: 0
    },
    techRequirements: ['tech_cannon1'],
    productionTime: 1,
    features: []
  },
  {
    id: 'unit_b12',
    description: '',
    name: 'B12',
    shootingSpeed: 600,
    accuracy: 95,
    evasion: 10,
    endurance: 2000,
    firePower: 400,
    strategicCaliber: 400,
    armorType: Sco.Model.ArmorType.MEDIUM,
    weaponType: Sco.Model.WeaponType.NORMAL,
    type: Sco.Model.UnitType.LAND,
    speed: 0,
    gasConsumption: 0,
    foodConsumption: 1,
    cost: {
      GL: 250,
      IR: 15,
      MO: 0
    },
    techRequirements: ['tech_cannon2'],
    productionTime: 1,
    features: []
  },
  {
    id: 'unit_b18',
    description: '',
    name: 'B18',
    shootingSpeed: 600,
    accuracy: 100,
    evasion: 8,
    endurance: 2500,
    firePower: 500,
    strategicCaliber: 500,
    armorType: Sco.Model.ArmorType.MEDIUM,
    weaponType: Sco.Model.WeaponType.ANTIARMOR,
    type: Sco.Model.UnitType.LAND,
    speed: 0,
    gasConsumption: 0,
    foodConsumption: 1,
    cost: {
      GL: 300,
      IR: 20,
      MO: 0
    },
    techRequirements: ['tech_cannon2'],
    productionTime: 2,
    features: []
  }
];
